<h2>Media Artefact</h2>
<p>
<span>published at <?= $this->creation ?> by <?= htmlentities($this->maker) ?></span>
</p>
<div class="profile row-fluid">
    <div class="span8">
        <img class="img-polaroid" src="<?= htmlentities($this->image) ?>" />
    </div>

    <div class="span4">
    <a class="btn btn-block" href="<?= htmlentities($this->feed) ?>">Show Activity Feed</a>
    <hr />
    <form method="post" action="?c=media&amp;a=tag">
        <div class="input-append">
            <input type="hidden" name="image" value="<?= htmlentities($this->resourceUri) ?>" />
            <input type="text" name="person" placeholder="Add a persons URI" /><button class="btn btn-primary" type="submit">Tag</button>
        </div>
    </form>
    <hr />
    <?php
    $this->partial(
        'activitystream.phtml',
        array(
            'activities' => $this->activities,
            'personUri' => $this->maker, // This is a placeholder
            'personName' => 'Image', // This is a placeholder
            'home' => false
        )
    );
    ?>
    </div>
</div>
