<ul class="nav">
    <li>
        <div class="btn-group">
            <?php if (count($this->notifications) > 0): ?>
            <a href="?c=notification&amp;a=getnew" class="btn">
                <span class="badge badge-info" title="<?php echo count($this->notifications) ?> Notifications"><?= count($this->notifications) ?></span>
            </a>
            <?php endif; ?>
            <a href="?c=user&amp;a=home" class="btn">
                <i class="icon-user"></i> <?= $this->username ?>
            </a>
        </div>
    </li>
</ul>
<div class="nav-collapse">
<ul class="nav">
    <li><a href="?c=profile&amp;a=list">List All Profiles</a></li>
</ul>
<ul class="nav pull-right">
    <?php
    if ($this->username != "guest")
    {
        echo ("<li><a href=\"?c=conference&amp;a=list\">Show All Conferences</a></li>");
        //echo ("<li><a href=\"?c=conference&amp;a=edit\">Conference Editor</a></li>");
        echo ("<li><a href=\"?c=editor&amp;a=edit&amp;class=person\">Profile Editor</a></li>");
        echo ("<li><a href=\"?c=application&amp;a=logout\">Logout</a></li>");
    }
    else
    {
        echo ("<li><a href=\"?c=application&amp;a=login\">Login</a></li>");
    }
    ?>
</ul>
</div>
<!--/.nav-collapse -->
