<h2>Profil Editor</h2>
<<form action="?c=application&amp;a=login" method="post" class="form-horizontal">
<fieldset>
<div class="control-group">
    <label class="control-label" for="username">Username</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="username" id="username" />
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="password">Password</label>
    <div class="controls">
        <input type="password" class="input-xlarge" name="password" id="password" /><br />
    </div>
</div>
<div class="form-actions">
    <button class="btn btn-primary" type="submit">Login</button>
</div>
<p>Dies ist die Seite für den Profileditor.</p>
</fieldset>
</form>

