<h2>Profil Editor</h2>
<form action="?c=user&amp;a=edit" method="post" class="form-horizontal">
<fieldset>
<div class="control-group">
    <label class="control-label" for="username">A</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="a" id="a" />
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="password">B</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="b" id="b" /><br />
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="password">C</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="c" id="c" /><br />
    </div>
</div>
<div class="form-actions">
    <button class="btn btn-primary" type="submit">Login</button>
</div>
<p>Dies ist die Seite für den Profileditor.</p>
</fieldset>
</form>

