<h2>Activity</h2>

<div class="activity row-fluid">
    <div class="span8">
<dl>
<dt>Date: </dt>
<dd id="date"><?= $this->date ?></dd>
<dt>Actor: </dt>
<dd id="actor"><?= $this->actor ?></dd>
<dt>Verb: </dt>
<dd id="verb"><?= $this->verb ?></dd>
<dt>Object: </dt>
<dd id="object"><?= $this->object ?></dd>
</dl>
</div>
<div class="span4">
<a class="btn btn-block" href="<?= htmlentities($this->feed) ?>">Show Activity Feed</a>
<hr />
<?php
$this->partial(
    'activitystream.phtml',
    array(
        'activities' => $this->activities,
        'personUri' => $this->maker, // This is a placeholder
        'personName' => 'Activity', // This is a placeholder
        'home' => false
    )
);
?>
</div>
