<?php echo '<?xml version="1.0" encoding="utf-8"?>' ?>

<feed xmlns="http://www.w3.org/2005/Atom" xmlns:activity="http://activitystrea.ms/schema/1.0/">
    <title>Activity Feed of <?= htmlentities($this->name) ?></title>
    <id><?= htmlentities($this->uri) ?></id>
    <link rel="hub" href="<?= htmlentities($this->hub) ?>"/>
    <link rel="self" type="application/atom+xml" href="<?= htmlentities($this->feedUri) ?>"/>
    <updated><?= $this->updated ?></updated>
    <?php foreach ($this->activities as $activity) : ?>
    <entry>
      <title><?= htmlentities($activity['title']) ?></title>
      <id><?= htmlentities($activity['uri']) ?></id>
      <link href="<?= htmlentities($activity['uri']) ?>" />
      <published><?= $activity['pubDate'] ?></published>
      <updated><?= $activity['pubDate'] ?></updated>
      <author>
        <name><?= $activity['author'] ?></name>
        <uri><?= htmlentities($activity['authorUri']) ?></uri>
      </author>
      <activity:verb><?= $activity['verb'] ?></activity:verb>
      <activity:object>
        <id><?= htmlentities($activity['object']) ?></id>
        <?php if (isset($activity['objectContent'])) : ?>
        <content><?= $activity['objectContent'] ?></content>
        <?php endif; ?>
        <?php if (isset($activity['objectPubDate'])) : ?>
        <published><?= $activity['objectPubDate'] ?></published>
        <?php endif; ?>
        <activity:object-type>
        <?php if (isset($activity['objectType'])) : ?>
          <?= $activity['objectType'] ?>
        <?php else : ?>
          Linked Data
        <?php endif; ?>
        </activity:object-type>
      </activity:object>
      <?php if (isset($activity['context'])) : ?>
      <activity:target>
        <id><?= htmlentities($activity['context']) ?></id>
        <?php if (isset($activity['contextType'])) : ?>
          <activity:object-type><?= $activity['contextType'] ?></activity:object-type>
        <?php else : ?>
          <activity:object-type>Linked Data</activity:object-type>
        <?php endif; ?>
      </activity:target>
      <?php endif; ?>
      <content>New Activity: <?= htmlentities($activity['title']) ?>
      <?php if (isset($activity['objectContent'])) : ?>
         : <?= $activity['objectContent'] ?>
      <?php endif; ?>
      </content>
    </entry>
    <?php endforeach; ?>
</feed>