<h2>Profil Editor</h2>
<form action="?c=person&amp;a=edit" method="post" class="form-horizontal">
<fieldset>

<?php

if (isset($this->profile))
{
    $multiple = $this->multiple;
    //var_dump($multiple);
    echo ("<div><input type=\"hidden\" class=\"input-xlarge\" name=\"multiple\" id=\"multiple\" value=\"$multiple\"/></div>");
    foreach ($this->profile as $key => $element)
    {
        //DONE: Filtern von z.B. foaf:knows
        //DONE: Ressourcen gar nicht zeigen.
        //DONE: Array für erwünschte Prädikate definieren --> Was darf editiert werden?
        //DONE: und danach filtern.
        //PARTLY DONE: Unterscheidung zwischen Single und Multiple-Prädikaten
        //PARTLY DONE: Diff: Alte Werte löschen!

        $keyX = $element["p"];
        $elementX = $element["o"];
        if (in_array($keyX, $this->allowedPrefixes))
        {
            if ($multiple)
            {
                echo ("Multiple Stuff not supperted. Yet.");
            }
            else
            {
                echo ("<div class=\"control-group\">
                <label class=\"control-label\" for=\"$keyX\">$keyX</label>
                <div class=\"controls\">
                <input type=\"text\" class=\"input-xlarge\" name=\"$keyX\" id=\"$key\" value=\"$elementX\"/>
                <input type=\"hidden\" class=\"input-xlarge\" name=\"$keyX-old\" id=\"$key-old\" value=\"$elementX\"/>
                </div>
                </div>");
            }
        }
    }
}
else
{
    echo ("Damn, profile not set...");
}

?>

<div class="form-actions">
    <button class="btn btn-primary" type="submit">Edit</button>
</div>

</fieldset>


</form>

