<h2>Profil Editor</h2>
<form action="?c=person&amp;a=edit" method="post" class="form-horizontal">
<fieldset>
<div class="control-group">
    <label class="control-label" for="Nick">Nick</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="Nick" id="nick" value="FooBar"/>
    </div>
</div>
<!-- <div class="control-group">
    <label class="control-label" for="username">B</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="b" id="b" /><br />
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="username">C</label>
    <div class="controls">
        <input type="text" class="input-xlarge" name="c" id="c" /><br />
    </div>
</div>
-->
<div class="form-actions">
    <button class="btn btn-primary" type="submit">Edit</button>
</div>

<p>Dies ist die Seite für den Profileditor.</p>

<p>Ein paar Tests:<br><?php echo("test") ?> <br> <?php echo(getUser) ?></p>

</fieldset>
</form>

