<h2>Profil Editor</h2>
<form action="?c=person&amp;a=edit" method="post" class="form-horizontal">
<fieldset>

<?php

if (isset($this->profile))
{
    var_dump($this->profile);

    foreach ($this->profile as $key => $element)
    {
	//TODO: Filtern von z.B. foaf:knows
	//Ressourcen gar nicht zeigen.	
	//Array für erwünschte Prädikate definieren --> Was darf editiert werden?
	//und danach filtern.
	//Unterscheidung zwischen Single und Multiple-Prädikaten
	//Diff: Alte Werte löschen!

	//if (!$allowedfields.contains($key))
	//{
	//	break;
	//}

        //var_dump($element);
        //echo ("<hr>");

echo ("<div class=\"control-group\">
<label class=\"control-label\" for=\"$key\">$key</label>
<div class=\"controls\">
<input type=\"text\"class=\"input-xlarge\" name=\"$key\" id=\"§key\" value=\"$element\"/>
<input type=\"hidden\"class=\"input-xlarge\" name=\"$key-old\" id=\"§key-old\" value=\"$element\"/>
</div>
</div>");
    }
}
else
{
    echo ("Damn, profile not set...");
}

?>

<div class="form-actions">
    <button class="btn btn-primary" type="submit">Edit</button>
</div>

</fieldset>


</form>

