<div class="profile row-fluid">
    <div class="span9">
        <h2>Profile of <?= $this->profileshowName ?><?php if(isset($this->profileshowNick)) : ?> (“<?= $this->profileshowNick ?>”)<?php endif; ?></h2>
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h3>Activities</h3>
        <?php if (isset($this->profileshowActivities) && count($this->profileshowActivities) > 0) : ?>
        <?php foreach ($this->profileshowActivities as $activity) : ?>
        <div class="activity well well-small">
            <div class="row-fluid">
                <form method="post" action="?c=activity&amp;a=replyForm">
                    <div class="span10">
                        <?php if (isset($activity['objectType'])) : ?>
                        <a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-important"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
                        <?php if(isset($activity['objectContent'])) : ?>
                        <a href="<?= htmlentities($activity['object']) ?>"> <?= Saft_Tools::getSpokenWord($activity['objectContent']) ?></a><br>at <?= $activity['pubDate'] ?>
                        <?php else : ?>
                        <a href="<?= htmlentities($activity['object']) ?>"><?= htmlentities($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
                        <?php endif; ?>
                        <?php else : ?>
                        <a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-info"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
                        <a  href="<?= htmlentities($activity['object']) ?>"> <?= Saft_Tools::getSpokenWord($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
                        <?php endif; ?>
                    </div>
                    <div class="span2">
                        <input type="hidden" name="object" value="<?= htmlentities($activity['uri'])?>" />
                        <input type="hidden" name="actor" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                        <a class="btn btn-mini btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($activity['object']) ?>">Show Feed of Object</a>
                        <button class="btn btn-mini btn-block" type="submit">Reply</button>
                    </div>
                    <?php if(isset($activity['objectImage'])) : ?>
                        <div class="span10">
                            <a href="<?= htmlentities($activity['object']) ?>"><img class="avatar size128 img-polaroid" src="<?= $activity['objectImage'] ?>"></img></a>
                        </div>
                    <?php endif; ?>
                </form>
            </div>
        </div>
        <?php endforeach; ?>
        <?php else: ?>
        <div class="alert alert-info">
            <?= $this->profileshowName ?> as no activities so far
        </div>
        <?php endif; ?>
    </div>
    <div class="span3">
        <form method="post" action="?c=person&amp;a=addfriend">
            <?php if ($this->profileshowLoggedIn) : ?>
            <input type="hidden" name="person" value="<?= htmlentities($this->profileshowLogInUri) ?>" />
            <input type="hidden" name="friend" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
            <button class="btn btn-block" type="submit">Add <?= $this->profileshowName ?> as Friend</button>
            <?php else : ?>
            <button class="btn btn-block disabled" disabled="disabled" type="submit">Add <?= $this->profileshowName ?> as Friend</button>
            <?php endif; ?>
        </form>
        <a class="btn btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
        <hr />
        <?php
            $this->partial(
                'friendlist.phtml',
                array('personUri' => $this->profileshowPersonUri, 'knows' => $this->profileshowKnows, 'addFriend' => false)
            );
        ?>
    </div>
</div>
