<div class="profile row-fluid">
    <div class="span9">
        <h2>Profile of <?= $this->profileshowName ?><?php if(isset($this->profileshowNick)) : ?> (“<?= $this->profileshowNick ?>”)<?php endif; ?></h2>
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h3>Activities</h3>
        <?php
            $this->partial(
                'activitystream.phtml',
                array(
                    'activities' => $this->profileshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName
                )
            );
        ?>
    </div>
    <div class="span3">
        <?php if ($this->profileshowLoggedIn) : ?>
            <form method="post" action="?c=person&amp;a=addfriend">  
                <input type="hidden" name="person" value="<?= htmlentities($this->profileshowLogInUri) ?>" />
                <input type="hidden" name="friend" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                <button class="btn btn-block" type="submit">Add <?= $this->profileshowName ?> as Friend</button>
        <?php else : ?>
            <form method="post" action="?c=person&amp;a=delFriend">
                <input type="hidden" name="person" value="<?= htmlentities($this->profileshowLogInUri) ?>" />
                <input type="hidden" name="friend" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                <button class="btn btn-block btn-danger" type="submit">Unfriend</button>
        <?php endif; ?>
        </form>
        <a class="btn btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
        <hr />
        <?php
            $this->partial(
                'friendlist.phtml',
                array('personUri' => $this->profileshowPersonUri, 'knows' => $this->profileshowKnows, 'addFriend' => false)
            );
        ?>
    </div>
</div>
