<h2>Login</h2>

<fieldset>
		<div class="form-actions">
			<form action="?c=oauth&amp;a=redirect" method="post" class="form-horizontal">
    			<button class="btn btn-primary" name="login" type="submit">Login with OAuth</button>
			</form>
    		<form action="?c=google&amp;a=redirect" method="post" class="form-horizontal">
    			<button class="btn btn-primary" name="login" type="submit">Login with Google</button>
			</form>
		</div>	
</fieldset>

