<?php if (!isset($this->profile)): ?>
<span>Sorry, the profile is not set.</span>
        <?= var_export($_POST, true) ?>
        <?= var_export($this->diff, true) ?>

<?php else : ?>

<h2>Edit resource</h2>
<form action="?c=editor&amp;a=edit&amp;class=<?= $this->caption ?>&amp;id=<?= urlencode($this->id) ?>" method="post" class="form-horizontal">
<fieldset>
    <legend>
<p><?= htmlentities($this->id) ?></p>
    </legend>
<?php if (isset($this->info)) : ?>
<div class="alert alert-success">
<?= $this->info ?>
</div>
<?php endif;
if (isset($this->error)) : ?>
<div class="alert alert-error">
<?= $this->error ?>
</div>
<?php endif; ?>

<?php
    if (isset($this->diff)) {
        var_dump($this->diff);
    }
?>

<?php
$countMax = 0;
foreach ($this->profile[$this->id] as $predicate => $objects) :
    $predicateTitle = $predicate; // TODO use title helper
?>
    <div class="control-group">
        <label class="control-label" for="<?= $predicate ?>"><?= $predicateTitle ?></label>
        <div class="controls">
<?php
    $count = 0;
    foreach ($objects as $object) :
        $value = $object['value'];
        $type = $object['type'];
        if (isset($this->wrong) && isset($this->wrong[$predicate]) && in_array($value, $this->wrong[$predicate])) {
            $thisIsWrong = true;
        } else {
            $thisIsWrong = false;
        }
    ?>
            <input type="hidden" name="newValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][type]" value="<?= htmlentities($type) ?>"/>
            <input type="text" name="newValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][value]" value="<?= htmlentities($value) ?>"/>
            <a href="javascript:deleteProperty('<?= $predicate ?>')">-</a>
            <?= $thisIsWrong ? '<i class="icon-warning-sign"></i>' : '' ?>
            <br />
<?php
        $added = false;
        if (isset($this->diff['add'][$this->id][$predicate])) {
            foreach ($this->diff['add'][$this->id][$predicate] as $object) {
                if ($object['value'] == $value && $object['type'] == $type) {
                    $added = true;
                    break;
                }
            }
        }
        if (!$added) :
?>
            <input type="hidden" name="originalValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][type]" value="<?= htmlentities($type) ?>" />
            <input type="hidden" name="originalValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][value]" value="<?= htmlentities($value) ?>" />
<?php
        endif;
        $count++;
    endforeach;
    $countMax = max($countMax, $count);
?>
            <a href="javascript:appendPropertyGroup('<?= $predicate ?>')">+</a>
        </div>
    </div>
<?php endforeach; ?>
<div class="form-actions">
    <button class="btn btn-primary" type="submit">Save</button>
</div>
</fieldset>
<?php
        if (isset($this->diff['delete'][$this->id])) :
    foreach ($this->diff['delete'][$this->id] as $predicate => $objects) :
        $count = $countMax;
        foreach ($objects as $object):
            $value = $object['value'];
            $type = $object['type'];
?>
            <input type="hidden" name="originalValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][type]" value="<?= htmlentities($type) ?>" />
            <input type="hidden" name="originalValues[<?= $this->id ?>][<?= $predicate ?>][<?= $count ?>][value]" value="<?= htmlentities($value) ?>" />
<?php
            $count++;
        endforeach;
    endforeach;
endif;
?>
</form>
<script language="javascript" type="text/javascript">
function appendPropertyGroup (property) {
    this.append("<div></div>");
}
</script>
<?php endif; ?>
