<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:activity="http://activitystrea.ms/schema/1.0/">
    <title>Activity Feed for <?= $this->name ?></title>
    <id><?= $this->uri ?></id>
    <link rel="hub" href="<?= $this->hub ?>"/>
    <link rel="self" type="application/atom+xml" href="<?= $this->feedUri ?>"/>
    <updated><?= $this->updated ?></updated>

    <?php foreach ($this->activities as $activity) : ?>

    <entry>
      <title><?= $activity['title'] ?></title>
      <id><?= $activity['uri'] ?></id>
      <link href="<?= $activity['uri'] ?>" />
      <published><?= $activity['pubDate'] ?></published>
      <updated><?= $activity['pubDate'] ?></updated>
      <author>
        <name><?= $activity['author'] ?></name>
        <uri><?= $activity['authorUri'] ?></uri>
      </author>
      <activity:verb><?= $activity['verb'] ?></activity:verb>
      <activity:object>
        <id><?= $activity['object'] ?></id>
        <?php if (isset($activity['objectContent'])) : ?>

        <content><?= $activity['objectContent'] ?></content>
        <?php endif; ?>
        <?php if (isset($activity['objectPubDate'])) : ?>

        <published><?= $activity['objectPubDate'] ?></published>
        <?php endif; ?>
        <?php if (isset($activity['objectType'])) : ?>

        <activity:object-type><?= $activity['objectType'] ?></activity:object-type>
        <?php endif; ?>

      </activity:object>
    </entry>

    <?php endforeach; ?>

</feed>
