<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="resources/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link type="text/css" href="resources/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <style type="text/css">
      @media (min-width: 980px) {
        body {
          padding-top: 60px;
        }
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <script type="text/javascript" src="resources/jquery/jquery.js"></script>
    <script type="text/javascript" src="resources/bootstrap/js/bootstrap.js"></script>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#"><img src="resources/img/xodx_20.png" alt="Xodx" /></a>
                <div class="btn-group pull-right">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if (count($this->notifications) > 0): ?>
                        <span class="badge badge-info"><?= count($this->notifications) ?></span>
                        <?php endif; ?>
                        <i class="icon-user"></i>
                        <?= $this->username ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="?c=user&amp;a=getnotifications">Notifications</a></li>
                        <li class="divider"></li>
                        <li><a href="?c=application&amp;a=login">Login</a></li>
                        <li><a href="?c=application&amp;a=logout">Logout</a></li>
                    </ul>
                </div>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                <?php
                foreach ($this->_menuFiles as $menuFile) {
                    include $menuFile;
                }
                ?>
                </div>
                </div>
                <div class="span9">
                <?php
                foreach ($this->_contentFiles as $contentFile) {
                    include $contentFile;
                }
                ?>
            </div>
        </div>
    </div>

    <?php if (!empty($this->_debugLog)) : ?>

    <div class="debug" id="debugConsole">
        <h3>Debuglog:</h3>
        <pre>
<?= $this->_debugLog ?>
        </pre>
    </div>

    <?php endif; ?>
</body>
</html>
