<h2>Profile of ...</h2>
<?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
<div class="profile">
    <h3><?= $this->profileshowName ?></h3>
    <?php if(isset($this->profileshowNick)) : ?> <h4><?= $this->profileshowNick ?></h4> <?php endif; ?>
    <h5>knows ...</h5>
    <form method="post" action="?c=profile&a=addfriend">
    <ul>
<?php
foreach($this->profileshowKnows as $contact) :
if ($contact['name'] != null) {
    $name = $contact['name'];
} else {
    $name = $contact['contactUri'];
}
?>
        <li><a href="?c=profile&amp;a=show&amp;person=<?= urlencode($contact['contactUri']) ?>"><?= $name ?></a></li>
<?php endforeach; ?>
        <li>
            <div class="input-append">
                <input type="hidden" name="person" value="<?= $this->profileshowPersonUri ?>" />
                <input type="text" name="friend" /><button class="btn btn-primary" type="submit">Add</button>
            </div>
        </li>
    </ul>
    </form>
    <h2>Pings</h2>
    <ul>
    <?php foreach ($this->profileshowNews as $notification) : ?>
        <li><?= var_export($notification, true) ?></li>
    <?php endforeach; ?>
    </ul>
    <h2>Activities</h2>
    <?php if (isset($this->profileshowActivities)) : ?>
    <?php foreach ($this->profileshowActivities as $activity) : ?>
    <div class="activity">
      <p>
        <a href="<?= $activity['uri'] ?>"><strong><?= $activity['title'] ?></strong></a><br />
        <em><?= $activity['pubDate'] ?></em>
      </p>
      <p>
        <a href="<?= $activity['authorUri'] ?>"><?= $activity['authorUri'] ?></a>
        did <a href="<?= $activity['verb'] ?>"><?= $activity['verb'] ?></a>
        <?php if (isset($activity['objectType'])) : ?>

        an <a href="<?= $activity['objectType'] ?>"><?= $activity['objectType'] ?></a>
        <?php endif; ?>
        : <a href="<?= $activity['object'] ?>"><?= $activity['object'] ?></a>
        <?php if (isset($activity['objectContent'])) : ?>

        <?= $activity['objectContent'] ?>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
    <?php else: ?>
        <div class="well">
        There are not Activities of this person
        </div>
    <?php endif; ?>
    <h2>Add Activity ...</h2>
    <form method="post" action="?c=activity&a=addactivity">
        <table>
            <tr>
                <th>Actor</th>
                <td>
                    <?= $this->profileshowName ?>

                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                </td>
            </tr>
            <tr>
                <th>Verb</th>
                <td>
                    <select name="verb">
                        <option value="http://xmlns.notu.be/aair#Located" disabled="true">Located</option>
                        <option value="http://xmlns.notu.be/aair#Join" disabled="true">Join</option>
                        <option value="http://xmlns.notu.be/aair#MakeFriend" disabled="true">MakeFriend</option>
                        <option value="http://xmlns.notu.be/aair#MarkAsFavorite" disabled="true">MarkAsFavorite</option>
                        <option value="http://xmlns.notu.be/aair#Play" disabled="true">Play</option>
                        <option value="http://xmlns.notu.be/aair#Post" selected="true">Post</option>
                        <option value="http://xmlns.notu.be/aair#RSVP" disabled="true">RSVP</option>
                        <option value="http://xmlns.notu.be/aair#Save" disabled="true">Save</option>
                        <option value="http://xmlns.notu.be/aair#Share" disabled="true">Share</option>
                        <option value="http://xmlns.notu.be/aair#StartFollowing" disabled="true">StartFollowing</option>
                        <option value="http://xmlns.notu.be/aair#Tag" disabled="true">Tag</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>Object</th>
                <td>
                <table>
                    <tr>
                        <th>Type</th>
                        <td>
                            <select name="type">
                                <option value="http://xmlns.notu.be/aair#Note">Note</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>content</th>
                        <td><textarea name="content"></textarea></td>
                    </tr>
                </table>
                </td>
            </tr>
        </table>
        <button class="btn btn-primary" type="submit">Do</button>
    </form>
    <a href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
    <form method="post" action="?c=user&a=subscribe">
        <div class="input-append">
            <input type="hidden" name="user" value="<?= $this->profileshowPersonUri ?>" />
            <input type="text" name="feeduri" /><button class="btn btn-primary" type="submit">Subscribe</button>
        </div>
    </form>
</div>
