<div class="profile row-fluid">
    <div class="span9">
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h2>Hello <?= $this->profileshowName ?></h2>
        <h3>Notifications</h3>
        <?php if (isset($this->profileshowNews) && count($this->profileshowNews) > 0) : ?>
        <ul>
            <?php foreach ($this->profileshowNews as $noteUri => $notification) : ?>
            <li><a href="<?= $noteUri ?>"><?= var_export($notification, true) ?></a></li>
            <?php endforeach; ?>
        <?php else: ?>
        <div class="alert alert-info">
            There are no notifications for you
        </div>
        <?php endif; ?>
        </ul>
        <h3>Activities</h3>
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
            <li><a href="#photo" data-toggle="tab">Photo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <textarea placeholder="Write a status note" class="input-block-level" name="content"></textarea>
                    <input type="hidden" name="verb" value="Post"  >
                    <input type="hidden" name="type" value="Note" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <input placeholder="Share a link" class="input-block-level" type="text" name="content" />
                    <input type="hidden" name="verb" value="Share" />
                    <input type="hidden" name="type" value="Bookmark" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value="false" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
            <div class="tab-pane" id="photo">
                <form enctype="multipart/form-data" method="post" action="?c=activity&amp;a=addactivity">
                    <input type="file" name="content"/>
                    <input type="hidden" name="verb" value="Post" />
                    <input type="hidden" name="type" value="Photo" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
        <?php if (isset($this->profileshowActivities) && count($this->profileshowActivities) > 0) : ?>
        <?php foreach ($this->profileshowActivities as $activity ) : ?>
        <div class="activity well well-small">
            <div class="row-fluid">
                <form method="post" action="?c=activity&amp;a=replyForm" class="form-inline">
                    <div class="span10">
                        <a href="<?= htmlentities($activity['authorUri']) ?>"><?= htmlentities($activity['author']) ?></a>
                        <?php if (isset($activity['objectType'])) : ?>
                        <a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-important"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
                        <?php if(isset($activity['objectContent'])) : ?>
                        <a href="<?= htmlentities($activity['object']) ?>"><?= Saft_Tools::getSpokenWord($activity['objectContent']) ?></a><br />
                        at <?= $activity['pubDate'] ?>
                        <?php else : ?>
                        <a href="<?= htmlentities($activity['object']) ?>"><?= htmlentities($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
                        <?php endif; ?>
                        <?php else : ?>
                        <a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-info"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
                        <a  href="<?= htmlentities($activity['object']) ?>"> <?= Saft_Tools::getSpokenWord($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
                        <?php endif; ?>
                    </div>
                    <div class="span2">
                        <input type="hidden" name="object" value="<?= htmlentities($activity['uri'])?>" />
                        <input type="hidden" name="actor" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                        <a class="btn btn-mini btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($activity['object']) ?>">Show Feed of Object</a>
                        <button class="btn btn-mini btn-block" type="submit">Reply</button>
                    </div>
                </form>
            </div>
        </div>
        <?php endforeach; ?>
        <?php else: ?>
        <div class="alert alert-info">
            You have no activities so far
        </div>
        <?php endif; ?>
    </div>
    <div class="span3">
        <a class="btn btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
        <hr />
        <h3>Friends</h3>
        <form method="post" action="?c=profile&amp;a=addfriend">
            <div class="input-append">
                <input type="hidden" name="person" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                <input type="text" name="friend" placeholder="Add a friends URI" /><button class="btn btn-primary" type="submit">Add</button>
            </div>
        </form>
        <?php foreach($this->profileshowKnows as $contact) : ?>
        <address>
            <?php
                if ($contact['name'] != null) {
                    $name = $contact['name'];
                } elseif ($contact['nick'] != null) {
                    $name = $contact['nick'];
                } else {
                    $name = "unknown name";
                }
            ?>
            <strong><?= $name ?></strong><br />
            <a href="?c=person&amp;uri=<?= urlencode($contact['contactUri']) ?>"><?= $contact['contactUri'] ?></a>
        </address>
        <?php endforeach; ?>
    </div>
</div>
