<div class="container-fluid">
    <h2>Home of ...</h2>
    <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
    <div class="profile row-fluid">
        <div class="span9">
        <h3><?= $this->profileshowName ?></h3>
        <?php if(isset($this->profileshowNick)) : ?> <h4><?= $this->profileshowNick ?></h4> <?php endif; ?>
                    <h2>Pings</h2>
                    <ul>
                    <?php foreach ($this->profileshowNews as $notification) : ?>
                        <li><?= var_export($notification, true) ?></li>
                    <?php endforeach; ?>
                    </ul>
                    <h2>Add Activity ...</h2>
                    <strong>Actor:</strong> <?= $this->profileshowName ?>
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <ul class="nav nav-pills">
                        <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
                        <li><a href="#link" data-toggle="tab">Link</a></li>
                        <li><a href="#photo" data-toggle="tab">Photo</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="status">
                            <form method="post" action="?c=activity&amp;a=addactivity">
                                <textarea name="content"></textarea>
                                <input type="hidden" name="verb" value="Post"  >
                                <input type="hidden" name="type" value="Note" />
                                <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                                <input type="hidden" name="reply" value=false />
                                <button class="btn btn-primary" type="submit">Post</button>
                            </form>
                        </div>
                        <div class="tab-pane" id="link">
                            <form method="post" action="?c=activity&amp;a=addactivity">
                                <input type="text" name="content" />
                                <input type="hidden" name="verb" value="Share" />
                                <input type="hidden" name="type" value="Bookmark" />
                                <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                                <input type="hidden" name="reply" value="false" />
                                <button class="btn btn-primary" type="submit">Share</button>
                            </form>
                        </div>
                        <div class="tab-pane" id="photo">
                            <form enctype="multipart/form-data" method="post" action="?c=activity&amp;a=addactivity">
                                <input type="file" name="content"/>
                                <input type="hidden" name="verb" value="Post" />
                                <input type="hidden" name="type" value="Photo" />
                                <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                                <input type="hidden" name="reply" value=false />
                                <button class="btn btn-primary" type="submit">Share</button>
                            </form>
                        </div>
                    </div>
                    <a href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
                        <form method="post" action="?c=user&amp;a=subscribe">
                            <div class="input-append">
                            <input type="hidden" name="user" value="<?= $this->profileshowPersonUri ?>" />
                            <input type="text" name="feeduri" /><button class="btn btn-primary" type="submit">Subscribe</button>
                            </div>
                        </form>
                    <h2>Activities</h2>
                    <?php if (isset($this->profileshowActivities)) : ?>
	                <?php foreach ($this->profileshowActivities as $activity ) : ?>
                    <div class="activity well">
		                    <div class="row-fluid">
		                <form method="post" action="?c=activity&amp;a=replyForm">
				            <div class="span10">
	    				<a href="<?= htmlentities($activity['authorUri']) ?>"><?= htmlentities($activity['author']) ?></a> 
        				<?php if (isset($activity['objectType'])) { ?>
				<a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-important"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
				<?php if(isset($activity['objectContent'])) { ?>
						<a href="<?= htmlentities($activity['object']) ?>"> <?= Saft_Tools::getSpokenWord($activity['objectContent']) ?></a><br>at <?= $activity['pubDate'] ?>
					<?php } else { ?>
						<a href="<?= htmlentities($activity['object']) ?>"><?= htmlentities($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
				<?php } } else { ?>
				<a  href="<?= htmlentities($activity['verb']) ?>"><span class="label label-info"><?= Saft_Tools::getSpokenWord($activity['verb']) ?></span></a>
				<a  href="<?= htmlentities($activity['object']) ?>"> <?= Saft_Tools::getSpokenWord($activity['object']) ?></a><br>at <?= $activity['pubDate'] ?>
				<?php } ?>
    
	        			<input type="hidden" name="object"
	    				value="<?= htmlentities($activity['uri'])?>" /> <input
	        				type="hidden" name="actor"
	        				value="<?= htmlentities($this->profileshowPersonUri) ?>" />
	        			</div><div class="span2">
                    <a class="btn btn-mini btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($activity['object']) ?>">Show Feed of Object</a>
	    			<button class="btn btn-mini btn-block" type="submit">Reply</button>
				</div>
			</form>
		</div>
		</div>
            	<?php endforeach; ?>
                <?php else: ?>
                <div class="well">
                    There are not Activities of this person
                </div>
             <?php endif; ?>
        	</div>
        <div class="span3">
            <h5>Friends:</h5>
            <form method="post" action="?c=profile&amp;a=addfriend">
                <div class="row-fluid">
                <?php
                    foreach($this->profileshowKnows as $contact) :
                    if ($contact['name'] != null) {
                        $name = $contact['name'];
                    } elseif ($contact['nick'] != null) {
                        $name = $contact['nick'];
                    } else {
                        $name = "unknown name";
                    }
                ?>

                    <div><?= $name ?></div>
                    <div><a href="?c=profile&amp;a=show&amp;person=<?= urlencode($contact['contactUri']) ?>"><?= $contact['contactUri'] ?></a></div>
                <?php endforeach; ?>
                <br>
    	        <div class="input-append">
                    <input type="hidden" name="person" value="<?= htmlentities($this->profileshowPersonUri) ?>" />
                    <input type="text" name="friend" /><button class="btn btn-primary" type="submit">Add</button>
                </div>
           </form>
        </div>
</div>
