<div class="profile row-fluid">
    <div class="span9">
        <?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128 img-polaroid" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
        <h2>Hello <?= $this->profileshowName ?></h2>
        <h3>Notifications</h3>
        <?php if (isset($this->profileshowNews) && count($this->profileshowNews) > 0) : ?>
            <?php
                foreach ($this->profileshowNews as $noteUri => $notification) {
                    $this->partial('notification.phtml', array('notification' => $notification));
                }
            ?>
        <?php else: ?>
        <div class="alert alert-info">
            There are no notifications for you
        </div>
        <?php endif; ?>
        <h3>Activities</h3>
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
            <li><a href="#photo" data-toggle="tab">Photo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <textarea placeholder="Write a status note" class="input-block-level" name="content"></textarea>
                    <input type="hidden" name="verb" value="Post"  >
                    <input type="hidden" name="type" value="Note" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&amp;a=addactivity">
                    <input placeholder="Share a link" class="input-block-level" type="text" name="content" />
                    <input type="hidden" name="verb" value="Share" />
                    <input type="hidden" name="type" value="Bookmark" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value="false" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
            <div class="tab-pane" id="photo">
                <form enctype="multipart/form-data" method="post" action="?c=activity&amp;a=addactivity">
                    <input type="file" name="content"/>
                    <input type="hidden" name="verb" value="Post" />
                    <input type="hidden" name="type" value="Photo" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <input type="hidden" name="reply" value=false />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
        <?php
            $this->partial(
                'activitystream.phtml',
                array(
                    'activities' => $this->profileshowActivities,
                    'personUri' => $this->profileshowPersonUri,
                    'personName' => $this->profileshowName,
                    'home' => true
                )
            );
        ?>
    </div>
    <div class="span3">
        <a class="btn btn-block" href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
        <hr />
        <?php
            $this->partial(
                'friendlist.phtml',
                array('personUri' => $this->profileshowPersonUri, 'knows' => $this->profileshowKnows, 'addFriend' => true)
            );
        ?>
    </div>
</div>
